### ISSUE TITLE
Fail to build on Android

### ISSUE THREAD

**Issue by wemow** [Only-IceSoul/react-native-maskview#3]
When I try to build on Android, I get those error messages, not sure if's missing an installation step for Android?

> Task :react-native-maskview:androidJavadoc
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewNoneManager.java:5: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewNoneManager.java:7: error: package com.facebook.react.uimanager does not exist
import com.facebook.react.uimanager.ThemedReactContext;
                                   ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewNoneManager.java:8: error: package com.facebook.react.uimanager does not exist
import com.facebook.react.uimanager.ViewGroupManager;
                                   ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewNoneManager.java:10: error: cannot find symbol
public class MaskViewNoneManager extends ViewGroupManager<MaskViewNone> {
                                         ^
  symbol: class ViewGroupManager
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewNoneManager.java:18: error: cannot find symbol
    protected MaskViewNone createViewInstance(@NonNull ThemedReactContext reactContext) {
                                                       ^
  symbol:   class ThemedReactContext
  location: class MaskViewNoneManager
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskView.java:17: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewManager.java:5: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewManager.java:6: error: package com.facebook.react.uimanager does not exist
import com.facebook.react.uimanager.ThemedReactContext;
                                   ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewManager.java:7: error: package com.facebook.react.uimanager does not exist
import com.facebook.react.uimanager.ViewGroupManager;
                                   ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewManager.java:9: error: cannot find symbol
public class MaskViewManager extends ViewGroupManager<MaskView> {
                                     ^
  symbol: class ViewGroupManager
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewManager.java:17: error: cannot find symbol
    protected MaskView createViewInstance(@NonNull ThemedReactContext reactContext) {
                                                   ^
  symbol:   class ThemedReactContext
  location: class MaskViewManager
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:9: error: package com.facebook.react does not exist
import com.facebook.react.ReactPackage;
                         ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:10: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.NativeModule;
                                ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:11: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:12: error: package com.facebook.react.uimanager does not exist
import com.facebook.react.uimanager.ViewManager;
                                   ^
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:14: error: cannot find symbol
public class ReactNativeMaskviewPackage implements ReactPackage {
                                                   ^
  symbol: class ReactPackage
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:16: error: cannot find symbol
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
                                                  ^
  symbol:   class ReactApplicationContext
  location: class ReactNativeMaskviewPackage
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:16: error: cannot find symbol
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
                ^
  symbol:   class NativeModule
  location: class ReactNativeMaskviewPackage
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:21: error: cannot find symbol
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
                                                ^
  symbol:   class ReactApplicationContext
  location: class ReactNativeMaskviewPackage
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/ReactNativeMaskviewPackage.java:21: error: cannot find symbol
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
                ^
  symbol:   class ViewManager
  location: class ReactNativeMaskviewPackage
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewNoneManager.java:18: error: cannot find symbol
    protected MaskViewNone createViewInstance(@NonNull ThemedReactContext reactContext) {
                                               ^
  symbol:   class NonNull
  location: class MaskViewNoneManager
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewNoneManager.java:23: error: cannot find symbol
    public void setBackgroundColor(@NonNull MaskViewNone view, int backgroundColor) {
                                    ^
  symbol:   class NonNull
  location: class MaskViewNoneManager
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskView.java:61: error: cannot find symbol
    public void onDescendantInvalidated(@NonNull View child, @NonNull View target) {
                                         ^
  symbol:   class NonNull
  location: class MaskView
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskView.java:61: error: cannot find symbol
    public void onDescendantInvalidated(@NonNull View child, @NonNull View target) {
                                                              ^
  symbol:   class NonNull
  location: class MaskView
/Users/username/Code/work/project/apps/test/node_modules/react-native-maskview/android/src/main/java/com/jjlf/rnmaskview/MaskViewManager.java:17: error: cannot find symbol
    protected MaskView createViewInstance(@NonNull ThemedReactContext reactContext) {
                                           ^
  symbol:   class NonNull
  location: class MaskViewManager
25 errors

> Task :react-native-maskview:androidJavadoc FAILED

FAILURE: Build failed with an exception.

**Comment by Only-IceSoul** [comment]
are u using expo?

**Comment by wemow** [comment]
> are u using expo?

 Nope, plain react native project 0.66

**Comment by Only-IceSoul** [comment]
> > are u using expo?
> 
> Nope, plain react native project 0.66

Are you sure that your project has androidx ? Create a new project or use expo.
